// catalog reducer

export const CatalogActions = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
}

export const CertificateActions = {
  GET_CERTIFICATES: "GET_CERTIFICATES",
  GET_CERTIFICATES_SUCCESS: "GET_CERTIFICATES_SUCCESS",
  GET_CERTIFICATES_ERROR: "GET_CERTIFICATES_ERROR",
}

export const ReviewsActions = {
  GET_REVIEWS: "GET_REVIEWS",
  GET_REVIEWS_SUCCESS: "GET_REVIEWS_SUCCESS",
  GET_REVIEWS_ERROR: "GET_REVIEWS_ERROR",
}

export const FeedbackActions = {
  ADD_FEEDBACK: "ADD_FEEDBACK",
  ADD_FEEDBACK_SUCCESS: "ADD_FEEDBACK_SUCCESS",
  ADD_FEEDBACK_ERROR: "ADD_FEEDBACK_ERROR",
}


export const ResumeActions = {
  SEND_RESUME: "SEND_RESUME",
  SEND_RESUME_SUCCESS: "SEND_RESUME_SUCCESS",
  SEND_RESUME_ERROR: "SEND_RESUME_ERROR",
}